name: 🐞 Bug
description: File a bug/issue report
labels: [ "type: :bug: bug" ]

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: |
        Please search to see if an issue already exists for the bug you encountered.

        Tip: You can go to the [GitHub issue tab](https://github.com/AlexProgrammerDE/SoulFire/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+%3Abug%3A+bug%22) for a list of open issues
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Describe your issue
      description: What is the issue?
      placeholder: "After the update x feature broke. It gives me this message: '...'"
    validations:
      required: true
  - type: textarea
    attributes:
      label: How can we reproduce what you got?
      description: Please describe the steps for us to reproduce the issue. Screenshots are also very welcomed.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: false
  - type: input
    id: logs
    attributes:
      label: SoulFire/Error Logs
      description: |
        Replace the links below by a paste of your console logs.
        - https://gist.github.com
        - https://bin.birdflop.com
      placeholder: "<log url>"
    validations:
      required: false
  - type: markdown
    attributes:
      value: "----"
  - type: markdown
    attributes:
      value: "## Helpful info"
  - type: input
    id: swversion
    attributes:
      label: SoulFire Version
      description: "SoulFire says its version at startup."
      placeholder: "1.0.0"
    validations:
      required: true
