/**
 * This package contains the gRPC server implementation for
 * SoulFire. This is used to communicate with the client.
 * Definitions generated by the proto module.
 */
package com.soulfiremc.server.grpc;
