package com.soulfiremc.server.grpc;

public enum Resource {
  COMMAND_EXECUTION,
  COMMAND_COMPLETION,
  COMMAND_HISTORY,
  START_ATTACK,
  TOGGLE_ATTACK,
  STOP_ATTACK,
  AUTHENTICATE_MC_ACCOUNT,
  SUBSCRIBE_LOGS,
  SERVER_CONFIG
}
