name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
      after-version:
        description: 'Snapshot version after release'
        required: true

# FIXME: Entire secret keys should not be inherited, Use specific set of secrets explicitly instead.
# See this issue to learn more: https://github.com/zizmorcore/zizmor/issues/360
jobs:
  set-release-version:
    uses: soulfiremc-com/SoulFire/.github/workflows/set-version.yml@main
    permissions:
      contents: write
    with:
      version: ${{ inputs.version }}
      update_sdk: true
    secrets: inherit

  build:
    needs: set-release-version
    runs-on: blacksmith-2vcpu-ubuntu-2404
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.ref }}
          persist-credentials: false
      - name: Set up JDK 25
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version: '25'
          distribution: 'temurin'
          check-latest: true
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
      - name: Build with Gradle
        run: ./gradlew build test --stacktrace --scan -x test

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@cb021f9b36a51a7c6f18e4679b6fa2cb77a1260c # v6.3.0
        with:
          mode: COMMIT
          toTag: ${{ github.ref }}
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}",
              "commit_template": "- [`#{{SHORT_MERGE_SHA}}`](https://github.com/soulfiremc-com/SoulFire/commit/#{{MERGE_SHA}}) #{{TITLE}}",
              "categories": [
                {
                    "title": "## 🚀 Features",
                    "labels": ["feat", "feature"]
                },
                {
                    "title": "## 🐛 Fixes",
                    "labels": ["fix", "bug"]
                },
                {
                    "title": "## 🏎️ Performance",
                    "labels": ["perf"]
                },
                {
                    "title": "## 🏗 Refactor",
                    "labels": ["refactor"]
                },
                {
                    "title": "## 📝 Documentation",
                    "labels": ["docs"]
                },
                {
                    "title": "## 🔨 Build",
                    "labels": ["build", "chore", "ci"]
                },
                {
                    "title": "## 💅 Style",
                    "labels": ["style"]
                },
                {
                    "title": "## 🧪 Tests",
                    "labels": ["test"]
                },
                {
                    "title": "## 💬 Other",
                    "labels": []
                },
                {
                  "title": "## 📦 Dependencies",
                  "labels": ["dependencies"]
                }
              ],
              "empty_template": "no changes",
              "label_extractor": [
                {
                  "pattern": "^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test){1}(\\([\\w\\-\\.]+\\))?(!)?: ([\\w ])+([\\s\\S]*)",
                  "on_property": "title",
                  "target": "$1"
                }
              ],
              "custom_placeholders": [
                {
                  "name": "SHORT_MERGE_SHA",
                  "source": "MERGE_SHA",
                  "transformer": {
                    "pattern": "^([0-9a-f]{7})[0-9a-f]*$",
                    "target": "$1"
                  }
                }
              ]
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 # v3.0.3
        with:
          body: |
            ---
            > [!IMPORTANT]
            > These downloads are for users who want to host Dedicated Servers for SoulFire clients or use the CLI client of SoulFire.
            > This is not the right download if you want to use the GUI client for SoulFire, which is recommended for most users.
            > Instead you should look at the [SoulFireClient releases page](https://github.com/soulfiremc-com/SoulFireClient/releases).
            ---

            ${{ steps.github_release.outputs.changelog }}
          tag_name: ${{ inputs.version }}
          generate_release_notes: false
          draft: false
          prerelease: false
          target_commitish: main
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_unmatched_files: true
          name: SoulFire ${{ inputs.version }}
          preserve_order: true
          files: |
            dedicated-launcher/build/libs/SoulFireDedicated-${{ inputs.version }}.jar
            client-launcher/build/libs/SoulFireCLI-${{ inputs.version }}.jar
      - name: Announce new SoulFire release
        uses: tsickert/discord-webhook@b217a69502f52803de774ded2b1ab7c282e99645 # 7.0.0
        with:
          webhook-url: ${{ secrets.WEBHOOK_URL }}
          content: <@&850705047938793503> New SoulFire version released!
          embed-title: SoulFire ${{ inputs.version }}
          embed-description: SoulFire ${{ inputs.version }} has been released! Changelog and download can be found at https://github.com/soulfiremc-com/SoulFire/releases/tag/${{ inputs.version }}
          embed-color: 3312063
          embed-thumbnail-url: https://soulfiremc.com/logo.png

  deploy-javadoc:
    needs: build
    uses: soulfiremc-com/SoulFire/.github/workflows/deploy-javadoc.yml@main
    permissions:
      contents: write
    secrets: inherit

  deploy-docker:
    needs: build
    uses: soulfiremc-com/SoulFire/.github/workflows/docker-deploy.yml@main
    secrets: inherit

  publish-sdk:
    needs: build
    uses: ./.github/workflows/publish-sdk.yml
    permissions:
      contents: read
      id-token: write
    with:
      version: ${{ inputs.version }}
      publish_npm: true
      publish_pypi: true
      publish_jsr: true

  set-after-version:
    needs: [ deploy-javadoc, deploy-docker, publish-sdk ]
    uses: soulfiremc-com/SoulFire/.github/workflows/set-version.yml@main
    permissions:
      contents: write
    with:
      version: ${{ inputs.after-version }}
    secrets: inherit
